expiration: 300
_core:
  default_config_hash: RViccNnarW8cWYl6LGhaqdWxqCg0rNzyT3I6MtGB9ug
public_key: /Users/Keenan/Sites/revenant-api/credentials/public.key
private_key: /Users/Keenan/Sites/revenant-api/credentials/private.key
